K1 7 view contract performance Merge
Ditlog-Dev/ditlog-android pull request #6
Opened 2018-03-25 00:40 UTC by LazuliSound

2018-03-25 05:51 UTC, keychera requested changes
need modification
- erase static string `SERVER_URL`, and use `BuildConfig.WEBSERVICE_URL` instead

2018-03-25 05:51 UTC, keychera commented on app/src/main/java/id/ac/itb/ditlog/monitorandperformance/AsyncAddIndicator.java
>      public static final String SERVER_URL = "159.65.131.168:8080";
erase this, use `BuildConfig.WEBSERVICE_URL` instead to refer the webservice url

2018-03-25 05:51 UTC, keychera commented on app/src/main/java/id/ac/itb/ditlog/monitorandperformance/AsyncAddIndicator.java
>                  URL url = new URL("http://" + SERVER_URL + "/indicators");
use `BuildConfig.WEBSERVICE_URL` instead to refer the webservice url

2018-03-25 05:51 UTC, keychera commented on app/src/main/java/id/ac/itb/ditlog/monitorandperformance/ChooseIndicator.java
>          public static final String SERVER_URL = "159.65.131.168:8080";
erase this, use `BuildConfig.WEBSERVICE_URL` instead to refer the webservice url

2018-03-25 05:51 UTC, keychera commented on app/src/main/java/id/ac/itb/ditlog/monitorandperformance/ChooseIndicator.java
>                  URL url = new URL(rawUrl);
change `SERVER_URL` to  `BuildConfig.WEBSERVICE_URL` to refer the webservice url

2018-03-25 05:51 UTC, keychera commented on app/src/main/java/id/ac/itb/ditlog/monitorandperformance/ViewContractPerformance.java
> +        private static final String SERVER_URL = "159.65.131.168:8080";
erase this, use `BuildConfig.WEBSERVICE_URL` to refer the webservice url

2018-03-25 05:51 UTC, keychera commented on app/src/main/java/id/ac/itb/ditlog/monitorandperformance/ViewContractPerformance.java
> +                String rawUrl = "http://" + SERVER_URL + "/contracts?tahun=" + year;
change `SERVER_URL` to `BuildConfig.WEBSERVICE_URL` to refer the webservice url

2018-03-26 12:36 UTC, dayuputuari approved these changes
View contract performance has been working. Need integration with login and authorization token.

2018-03-26 12:43 UTC, keychera approved these changes

2018-03-26 12:45 UTC, merged